export const ECONOMY = {
  // Starting balance
  INITIAL_SPARK: 100,

  // Earning
  DAILY_LOGIN: 5,
  WEEKLY_STREAK_BONUS: 30,
  BATTLE_WIN: 20,
  BATTLE_LOSS: 5,
  BATTLE_DRAW: 10,
  FIRST_CARD_BONUS: 50,
  WIN_STREAK_3: 10,
  WIN_STREAK_5: 25,

  // Tournament rewards
  TOURNAMENT_DAILY_1ST: 100,
  TOURNAMENT_DAILY_2ND: 50,
  TOURNAMENT_WEEKLY_1ST: 300,
  TOURNAMENT_WEEKLY_2ND: 150,
  TOURNAMENT_WEEKLY_3RD: 75,
  TOURNAMENT_MONTHLY_1ST: 500,

  // Spending
  CARD_CREATION_COST: 10,
  CARD_EVOLUTION_COST: 30,
  DECK_SLOT_EXPANSION_COST: 100,
  AUCTION_FEE_PERCENT: 0.05,

  // Limits
  CARD_CREATION_COOLDOWN_MS: 5 * 60 * 1000, // 5 minutes
  CARD_CREATION_DAILY_LIMIT: 20,
  DECK_MIN_SIZE: 3,
  DECK_MAX_SIZE: 5,
  DECK_EXPANDED_MAX_SIZE: 7,
} as const;

export const ELO = {
  INITIAL_RATING: 1200,
  K_FACTOR: 32,
  WIN_MIN: 15,
  WIN_MAX: 30,
  LOSS_MIN: 10,
  LOSS_MAX: 20,
  MATCHMAKING_RANGE: 200,
  MATCHMAKING_EXPAND_INTERVAL_MS: 10_000, // expand range every 10s
  MATCHMAKING_EXPAND_AMOUNT: 50,
  MATCHMAKING_MAX_RANGE: 500,
} as const;
