export const ECONOMY = {
  // Starting balance
  INITIAL_SPARK: 100,

  // Earning
  DAILY_LOGIN: 5,
  WEEKLY_STREAK_BONUS: 30,
  BATTLE_WIN: 20,
  BATTLE_LOSS: 5,
  BATTLE_DRAW: 10,
  FIRST_CARD_BONUS: 50,
  WIN_STREAK_3: 10,
  WIN_STREAK_5: 25,

  // Tournament rewards
  TOURNAMENT_DAILY_1ST: 100,
  TOURNAMENT_DAILY_2ND: 50,
  TOURNAMENT_WEEKLY_1ST: 300,
  TOURNAMENT_WEEKLY_2ND: 150,
  TOURNAMENT_WEEKLY_3RD: 75,
  TOURNAMENT_MONTHLY_1ST: 500,

  // Spending
  CARD_CREATION_COST: 10,
  CARD_EVOLUTION_COST: 30,
  DECK_SLOT_EXPANSION_COST: 100,
  AUCTION_FEE_PERCENT: 0.05,

  // Limits
  CARD_CREATION_COOLDOWN_MS: 5 * 1000, // 5 seconds
  CARD_CREATION_DAILY_LIMIT: 20,
  DECK_MIN_SIZE: 3,
  DECK_MAX_SIZE: 5,
  DECK_EXPANDED_MAX_SIZE: 7,

  // Referrals
  REFERRAL_BONUS: 50,
  REFERRAL_MILESTONE_10_REWARD: 'guaranteed_legendary',

  // Card upgrades
  CARD_REFORGE_COST: 20,
  CARD_BOOST_COST: 15,
  CARD_BOOST_BATTLES: 5,
  CARD_BOOST_MULTIPLIER: 1.1,

  // Auction
  AUCTION_LISTING_FEE: 5,

  // Deck expansion tiers
  DECK_EXPANSION_7_COST: 100,
  DECK_EXPANSION_9_COST: 500,

  // Operator revenue share
  OPERATOR_BATTLE_SHARE: 0.10,
  OPERATOR_AUCTION_SHARE: 0.02,
  CREATOR_ROYALTY_PER_WIN: 1,

  // Season & events
  SEASON_SPARK_DECAY_THRESHOLD: 200,
  SEASON_SPARK_DECAY_RATE: 0.20,
  DOUBLE_SPARK_MULTIPLIER: 2,
  LEGENDARY_RAIN_PROBABILITY: 0.20,

  // Veteran system
  VETERAN_BATTLE_THRESHOLD: 100,
  VETERAN_STAT_BONUS: 0.05,
} as const;

export const ELO = {
  INITIAL_RATING: 1200,
  K_FACTOR: 32,
  WIN_MIN: 15,
  WIN_MAX: 30,
  LOSS_MIN: 10,
  LOSS_MAX: 20,
  MATCHMAKING_RANGE: 200,
  MATCHMAKING_EXPAND_INTERVAL_MS: 10_000, // expand range every 10s
  MATCHMAKING_EXPAND_AMOUNT: 50,
  MATCHMAKING_MAX_RANGE: 500,
} as const;
