import type { SkillPoolEntry } from "@molgame/shared";

export const SKILL_POOL: SkillPoolEntry[] = [
  // ===== FIRE SKILLS =====
  {
    skill_id: "sk_inferno_blast",
    name: "Inferno Blast",
    description: "Unleash a massive fireball that engulfs the target.",
    element: "fire",
    type: "attack",
    power: 60,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_flame_shield",
    name: "Flame Shield",
    description: "Surround yourself in flames, boosting DEF for 2 turns.",
    element: "fire",
    type: "buff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "def_up", value: 0.3, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_eruption",
    name: "Eruption",
    description: "Volcanic eruption dealing heavy fire damage.",
    element: "fire",
    type: "attack",
    power: 80,
    cost: 3,
    cooldown: 3,
    effects: [],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_burn",
    name: "Burn",
    description: "Set the target ablaze, dealing damage over 3 turns.",
    element: "fire",
    type: "attack",
    power: 30,
    cost: 1,
    cooldown: 2,
    effects: [{ type: "dot", value: 10, duration: 3 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_fire_dance",
    name: "Fire Dance",
    description: "A blazing dance that boosts ATK for 2 turns.",
    element: "fire",
    type: "buff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "atk_up", value: 0.25, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_meteor_strike",
    name: "Meteor Strike",
    description: "Call down a meteor for devastating fire damage.",
    element: "fire",
    type: "attack",
    power: 100,
    cost: 3,
    cooldown: 4,
    effects: [],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_blazing_fury",
    name: "Blazing Fury",
    description: "ATK +50% but DEF -20% for 2 turns.",
    element: "fire",
    type: "buff",
    power: 0,
    cost: 2,
    cooldown: 4,
    effects: [
      { type: "atk_up", value: 0.5, duration: 2 },
      { type: "def_down", value: 0.2, duration: 2 },
    ],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_ember_shot",
    name: "Ember Shot",
    description: "Quick fire attack with low cost.",
    element: "fire",
    type: "attack",
    power: 40,
    cost: 1,
    cooldown: 1,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_wildfire",
    name: "Wildfire",
    description: "Spread fire that reduces enemy DEF.",
    element: "fire",
    type: "attack",
    power: 50,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "def_down", value: 0.2, duration: 2 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_phoenix_flame",
    name: "Phoenix Flame",
    description: "Legendary fire that heals self while damaging enemy.",
    element: "fire",
    type: "attack",
    power: 70,
    cost: 3,
    cooldown: 4,
    effects: [{ type: "lifesteal", value: 0.3 }],
    rarity_min: "legendary",
  },

  // ===== WATER SKILLS =====
  {
    skill_id: "sk_tidal_wave",
    name: "Tidal Wave",
    description: "Crash a massive wave onto the opponent.",
    element: "water",
    type: "attack",
    power: 60,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_frost_armor",
    name: "Frost Armor",
    description: "Encase yourself in ice, boosting DEF for 2 turns.",
    element: "water",
    type: "buff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "def_up", value: 0.35, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_healing_rain",
    name: "Healing Rain",
    description: "Gentle rain restores HP.",
    element: "water",
    type: "heal",
    power: 40,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "heal", value: 40 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_freeze",
    name: "Freeze",
    description: "Freeze the target, reducing SPD for 2 turns.",
    element: "water",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "spd_down", value: 0.5, duration: 2 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_aqua_jet",
    name: "Aqua Jet",
    description: "A quick water strike that hits fast.",
    element: "water",
    type: "attack",
    power: 45,
    cost: 1,
    cooldown: 1,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_whirlpool",
    name: "Whirlpool",
    description: "Trap the target in a whirlpool, dealing damage over time.",
    element: "water",
    type: "attack",
    power: 35,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "dot", value: 15, duration: 2 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_ice_lance",
    name: "Ice Lance",
    description: "Pierce through defenses with a frozen lance.",
    element: "water",
    type: "attack",
    power: 70,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "ignore_def", value: 0.2 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_ocean_blessing",
    name: "Ocean's Blessing",
    description: "Deep sea magic that heals and boosts DEF.",
    element: "water",
    type: "heal",
    power: 30,
    cost: 2,
    cooldown: 4,
    effects: [
      { type: "heal", value: 30 },
      { type: "def_up", value: 0.2, duration: 2 },
    ],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_tsunami",
    name: "Tsunami",
    description: "Unleash the ultimate water devastation.",
    element: "water",
    type: "attack",
    power: 95,
    cost: 3,
    cooldown: 4,
    effects: [],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_absolute_zero",
    name: "Absolute Zero",
    description: "Freeze everything. Heavy damage + SPD reduction.",
    element: "water",
    type: "attack",
    power: 85,
    cost: 3,
    cooldown: 4,
    effects: [{ type: "spd_down", value: 0.4, duration: 2 }],
    rarity_min: "legendary",
  },

  // ===== LIGHTNING SKILLS =====
  {
    skill_id: "sk_thunder_strike",
    name: "Thunder Strike",
    description: "Call down lightning on the target.",
    element: "lightning",
    type: "attack",
    power: 55,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_static_field",
    name: "Static Field",
    description: "Generate a static field that reduces enemy ATK.",
    element: "lightning",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "atk_down", value: 0.25, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_chain_lightning",
    name: "Chain Lightning",
    description: "Lightning that chains between targets.",
    element: "lightning",
    type: "attack",
    power: 65,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_paralysis",
    name: "Paralysis",
    description: "Shock the target, reducing SPD drastically.",
    element: "lightning",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "spd_down", value: 0.6, duration: 1 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_spark_burst",
    name: "Spark Burst",
    description: "Quick electrical burst.",
    element: "lightning",
    type: "attack",
    power: 40,
    cost: 1,
    cooldown: 1,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_overcharge",
    name: "Overcharge",
    description: "Supercharge yourself. ATK and SPD up for 2 turns.",
    element: "lightning",
    type: "buff",
    power: 0,
    cost: 2,
    cooldown: 4,
    effects: [
      { type: "atk_up", value: 0.3, duration: 2 },
      { type: "spd_up", value: 0.3, duration: 2 },
    ],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_voltaic_surge",
    name: "Voltaic Surge",
    description: "Surge of electricity piercing through defenses.",
    element: "lightning",
    type: "attack",
    power: 75,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "ignore_def", value: 0.3 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_storm_call",
    name: "Storm Call",
    description: "Summon a storm for massive lightning damage.",
    element: "lightning",
    type: "attack",
    power: 90,
    cost: 3,
    cooldown: 4,
    effects: [],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_thunder_god",
    name: "Thunder God's Wrath",
    description: "Channel divine lightning. Ignores 50% DEF.",
    element: "lightning",
    type: "attack",
    power: 100,
    cost: 3,
    cooldown: 4,
    effects: [{ type: "ignore_def", value: 0.5 }],
    rarity_min: "legendary",
  },

  // ===== NATURE SKILLS =====
  {
    skill_id: "sk_vine_whip",
    name: "Vine Whip",
    description: "Strike with thorny vines.",
    element: "nature",
    type: "attack",
    power: 50,
    cost: 1,
    cooldown: 1,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_regeneration",
    name: "Regeneration",
    description: "Heal over time for 3 turns.",
    element: "nature",
    type: "heal",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "hot", value: 15, duration: 3 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_poison_spore",
    name: "Poison Spore",
    description: "Release toxic spores that poison the target.",
    element: "nature",
    type: "attack",
    power: 25,
    cost: 1,
    cooldown: 2,
    effects: [{ type: "dot", value: 12, duration: 3 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_root",
    name: "Root",
    description: "Entangle the target with roots, reducing SPD.",
    element: "nature",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "spd_down", value: 0.4, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_thorn_barrage",
    name: "Thorn Barrage",
    description: "Barrage of thorns dealing solid damage.",
    element: "nature",
    type: "attack",
    power: 60,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_natures_wrath",
    name: "Nature's Wrath",
    description: "The fury of nature unleashed.",
    element: "nature",
    type: "attack",
    power: 85,
    cost: 3,
    cooldown: 3,
    effects: [],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_bloom",
    name: "Bloom",
    description: "Full heal burst from nature's energy.",
    element: "nature",
    type: "heal",
    power: 60,
    cost: 2,
    cooldown: 4,
    effects: [{ type: "heal", value: 60 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_photosynthesis",
    name: "Photosynthesis",
    description: "Absorb light to heal and boost DEF.",
    element: "nature",
    type: "heal",
    power: 25,
    cost: 1,
    cooldown: 3,
    effects: [
      { type: "heal", value: 25 },
      { type: "def_up", value: 0.15, duration: 2 },
    ],
    rarity_min: "common",
  },
  {
    skill_id: "sk_world_tree",
    name: "World Tree's Blessing",
    description: "Legendary nature magic. Massive heal + ATK buff.",
    element: "nature",
    type: "heal",
    power: 80,
    cost: 3,
    cooldown: 4,
    effects: [
      { type: "heal", value: 80 },
      { type: "atk_up", value: 0.3, duration: 2 },
    ],
    rarity_min: "legendary",
  },

  // ===== SHADOW SKILLS =====
  {
    skill_id: "sk_phantom_strike",
    name: "Phantom Strike",
    description: "Shadow attack that ignores 30% of DEF.",
    element: "shadow",
    type: "attack",
    power: 65,
    cost: 2,
    cooldown: 2,
    effects: [{ type: "ignore_def", value: 0.3 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_dark_veil",
    name: "Dark Veil",
    description: "Cloak in shadows, boosting evasion for 1 turn.",
    element: "shadow",
    type: "buff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "evasion_up", value: 0.5, duration: 1 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_soul_drain",
    name: "Soul Drain",
    description: "Drain the target's life force. Lifesteal attack.",
    element: "shadow",
    type: "attack",
    power: 50,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "lifesteal", value: 0.4 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_curse",
    name: "Curse",
    description: "Place a dark curse, reducing ATK for 2 turns.",
    element: "shadow",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "atk_down", value: 0.3, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_shadow_bolt",
    name: "Shadow Bolt",
    description: "Quick bolt of dark energy.",
    element: "shadow",
    type: "attack",
    power: 45,
    cost: 1,
    cooldown: 1,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_nightmare",
    name: "Nightmare",
    description: "Inflict nightmares, reducing all stats.",
    element: "shadow",
    type: "debuff",
    power: 0,
    cost: 2,
    cooldown: 4,
    effects: [
      { type: "atk_down", value: 0.2, duration: 2 },
      { type: "def_down", value: 0.2, duration: 2 },
    ],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_void_slash",
    name: "Void Slash",
    description: "Slash through the void dealing heavy shadow damage.",
    element: "shadow",
    type: "attack",
    power: 80,
    cost: 2,
    cooldown: 3,
    effects: [],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_death_mark",
    name: "Death Mark",
    description: "Mark the target for death. Extra damage on next attack.",
    element: "shadow",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 4,
    effects: [{ type: "damage_taken_up", value: 0.4, duration: 1 }],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_abyss",
    name: "Abyss",
    description: "Open the abyss. Devastating shadow damage.",
    element: "shadow",
    type: "attack",
    power: 100,
    cost: 3,
    cooldown: 4,
    effects: [],
    rarity_min: "legendary",
  },

  // ===== LIGHT SKILLS =====
  {
    skill_id: "sk_holy_smite",
    name: "Holy Smite",
    description: "Strike with divine light.",
    element: "light",
    type: "attack",
    power: 55,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_divine_shield",
    name: "Divine Shield",
    description: "Summon a shield of light. DEF +40% for 2 turns.",
    element: "light",
    type: "buff",
    power: 0,
    cost: 2,
    cooldown: 3,
    effects: [{ type: "def_up", value: 0.4, duration: 2 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_purify",
    name: "Purify",
    description: "Cleanse all debuffs and heal slightly.",
    element: "light",
    type: "heal",
    power: 20,
    cost: 1,
    cooldown: 3,
    effects: [
      { type: "cleanse", value: 1 },
      { type: "heal", value: 20 },
    ],
    rarity_min: "common",
  },
  {
    skill_id: "sk_blind",
    name: "Blind",
    description: "Blind the target with radiant light. ATK down.",
    element: "light",
    type: "debuff",
    power: 0,
    cost: 1,
    cooldown: 3,
    effects: [{ type: "atk_down", value: 0.35, duration: 2 }],
    rarity_min: "common",
  },
  {
    skill_id: "sk_radiant_beam",
    name: "Radiant Beam",
    description: "A focused beam of pure light.",
    element: "light",
    type: "attack",
    power: 65,
    cost: 2,
    cooldown: 2,
    effects: [],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_sanctuary",
    name: "Sanctuary",
    description: "Create a holy sanctuary. Heal + DEF up.",
    element: "light",
    type: "heal",
    power: 35,
    cost: 2,
    cooldown: 4,
    effects: [
      { type: "heal", value: 35 },
      { type: "def_up", value: 0.25, duration: 2 },
    ],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_ray_of_light",
    name: "Ray of Light",
    description: "Quick light attack.",
    element: "light",
    type: "attack",
    power: 40,
    cost: 1,
    cooldown: 1,
    effects: [],
    rarity_min: "common",
  },
  {
    skill_id: "sk_judgment",
    name: "Judgment",
    description: "Pass divine judgment dealing massive light damage.",
    element: "light",
    type: "attack",
    power: 90,
    cost: 3,
    cooldown: 4,
    effects: [],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_divine_wrath",
    name: "Divine Wrath",
    description: "The wrath of the heavens. Ignores DEF entirely.",
    element: "light",
    type: "attack",
    power: 80,
    cost: 3,
    cooldown: 4,
    effects: [{ type: "ignore_def", value: 1.0 }],
    rarity_min: "legendary",
  },

  // ===== UNIVERSAL SKILLS =====
  {
    skill_id: "sk_last_stand",
    name: "Last Stand",
    description: "When HP below 20%, ATK doubles for 1 turn.",
    element: null,
    type: "buff",
    power: 0,
    cost: 1,
    cooldown: 4,
    effects: [{ type: "last_stand", value: 2.0, duration: 1 }],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_mirror",
    name: "Mirror",
    description: "Reflect 50% of received damage for 1 turn.",
    element: null,
    type: "buff",
    power: 0,
    cost: 2,
    cooldown: 4,
    effects: [{ type: "reflect", value: 0.5, duration: 1 }],
    rarity_min: "epic",
  },
  {
    skill_id: "sk_sacrifice",
    name: "Sacrifice",
    description: "Sacrifice 30% HP to deal fixed 100 damage.",
    element: null,
    type: "special",
    power: 100,
    cost: 2,
    cooldown: 4,
    effects: [{ type: "self_damage_percent", value: 0.3 }],
    rarity_min: "rare",
  },
  {
    skill_id: "sk_swap",
    name: "Swap",
    description: "Exchange ATK and DEF with the opponent for 2 turns.",
    element: null,
    type: "special",
    power: 0,
    cost: 2,
    cooldown: 4,
    effects: [{ type: "swap_stats", value: 1, duration: 2 }],
    rarity_min: "legendary",
  },
];
